# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/lamuguo/tmp/WordPress
    server: 10.0.0.5
---
# PersistentVolumeClaim for binlog
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: binlog-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# PersistentVolumeClaim for WordPress
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: wordpress-pv
  storageClassName: ""
