apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000  # 恢复 securityContext
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mysql.user }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mysql.database }}
            - name: TEC_TICKETS_EMAILS
              value: "1"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-volume
              mountPath: /var/www/html
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress-pvc
